### ISSUE TITLE
Add throws for InitializableConfigDialog

### ISSUE THREAD

**Issue by skodape** [UnifiedViews/Plugin-DevEnv#10]
It may be nice to see possibility to throw an ConfigException out of initialize method from 
https://github.com/UnifiedViews/Plugin-DevEnv/blob/develop/uv-dpu-api-helpers/src/main/java/eu/unifiedviews/helpers/dpu/config/InitializableConfigDialog.java

If all dialog initialization is placed into this method, then I need a way how to throw exception is something goes wrong.

+ may it be done in current version, as we are in "snapshot mode"?

**Comment by skrchnavy** [comment]
@skodape could be part of improvement of helpers #9

**Comment by skrchnavy** [comment]
@skodape / @tomas-knap : please update status, is the implementation finished?

**Comment by skodape** [comment]
Yes, see https://github.com/UnifiedViews/Plugin-DevEnv/blob/develop/uv-dpu-config-vaadin/src/main/java/eu/unifiedviews/dpu/config/vaadin/InitializableConfigDialog.java

The commit is unfortunately lost as it was in another repository.

**Comment by skrchnavy** [comment]
I see the change in this repo, see: a43f8e79935def0f376e8b9b145a2796470da269
