### ISSUE TITLE
Update of maven build infrastructure to use pom inheritance

### ISSUE THREAD

**Issue by skodape** [UnifiedViews/Plugin-DevEnv#14]
Why we have parent projet but we do not use it from modules?

Possible advantage is to locate common pom.xml content on one place in parent project.

**Comment by skrchnavy** [comment]
What is expect to be reused in modules pom files from such common pom?
We can use inheritance in modules but it must not be root pom but dedicated pom file if we see a benefit.

**Comment by skodape** [comment]
Java version, sesame version, licence?, repositories, setting for maven-compiler-plugin, maven-javadoc-plugin (good for java-8 update), ...

May I know the reason why not the root pom.xml, is this because of intergration test?

**Comment by skrchnavy** [comment]
When you start using parent pom, then you are pushed to have same version of modules even module is not changed.
When we split this repo into modules, the goal was to have all interface versions independent and also keep version of interface stable in case of more often changes in helpers.

**Comment by skodape** [comment]
I'm not sure with the version. We have common parent project for dpu and they may have different versions or is this given by some "policy"?

**Comment by skrchnavy** [comment]
We can start with parent pom (not root pom but special defined pom) and keep there only real common definitions.
As you mentioned, setting for maven-compiler-plugin, maven-javadoc-plugin are good candidates.

**Comment by skodape** [comment]
And the reason not to use root.pom? 

As using some other pom might not be easy and it will definitely not be a standard solution. We will have to locale it into some parent-project and then use rootPath etc .. 

If the reason not to use root pom.xml is that good maybe current state is the best solution although it's introduce some redundancy.

**Comment by mkl-eea-sk** [comment]
1. we have pom.xml in root folder and modules inside devenv repo declare this pom.xml as their parent. so we are using parent pom.
2. we are also using scheme, where parent pom is not the one in ../pom.xml (all plugins are children of dpu-base-pom/pom.xml) which is distributed using maven repository.
3. if you whish to move more and more common chunks from submodules to parent pom.xml - at your will. but beware, that, devenv repository holds loosely coupled modules, which are in fact independent in versioning, deploying etc. It is only our laziness, that we have these modules inside one repository, and maybe one day, we will split the repository.

**Comment by skrchnavy** [comment]
Regarding root.pom=parent.pom vs. independent root.pom and parent.pom - for mudular development it is good practice to use these modules independent. (Then you can create also good hierarchy)
see http://books.sonatype.com/mvnref-book/reference/pom-relationships-sect-pom-best-practice.html
*POM inheritance is very powerful, but it can be overused. When it makes sense to share dependencies and build configuration, a parent/child relationship should be used. When it doesn’t make sense is when there are distinct differences between two projects.*

**Comment by mkl-eea-sk** [comment]
@tomas-knap had some ideas and he is moving forward to realization, so let him do the things.

**Comment by skrchnavy** [comment]
@skodape / @tomas-knap is this already done? Or do you plan additional changes?
(also consider #21)

**Comment by skodape** [comment]
There is hierarchical structure now, but it's not optimal - as you suggested we should consider #21 and also there are some valuable comments/suggestions from Michal (in fact another issue can be created for them).

**Comment by skrchnavy** [comment]
@tomas-knap to follow this issue and provide proposals

**Comment by skrchnavy** [comment]
@tomas-knap this is blocking for release of 2.0.0

**Comment by tomas-knap** [comment]
Current status:

* root.pom just declares list of all modules to simplify build of all modules. 
* modules are based on paren pom "uv-pom"
* dependencies are declared correctly at the level where they are needed.

**Comment by tomas-knap** [comment]
See also: https://github.com/UnifiedViews/Plugin-DevEnv/issues/33, https://github.com/UnifiedViews/Plugin-DevEnv/issues/21, where further issues are described
