### ISSUE TITLE
sending message also with long text

### ISSUE THREAD

**Issue by skodape** [UnifiedViews/Plugin-DevEnv#2]
DPUContext.sendMessage(Type, ShortMessage, Exception) as DPU developers then put Exception message into long text (sendMessage(Type, ShortMessage, LongMessage) ) instead of exception (sendMessage(Type, ShortMessage, LongMessage, Exception)

**Comment by skrchnavy** [comment]
@tomas-knap please comment if useful, we can plan it in next release accordingly

**Comment by skodape** [comment]
I take it back, this should be done by helper of some sort in DPU space. There is no need to put this functionality into API as API provide enough general method.

**Comment by skrchnavy** [comment]
Issue closed, author suggested another way of implementation
