### ISSUE TITLE
Commit related to Cryptography interface must be reverted

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Plugin-DevEnv#20]
Commit https://github.com/UnifiedViews/Plugin-DevEnv/commit/a80d72cfa9af959cda6ea62acd61ded3956ed123 must be reverted, see the comments under the commit to see justification. 

It breaks the develop branch (DPUs cannot be imported to UV)

**Comment by tomas-knap** [comment]
caused https://github.com/UnifiedViews/Core/issues/319

**Comment by eea01** [comment]
Repaired in [this line](https://github.com/UnifiedViews/Core/commit/d986ae8c64268207021cf926eb5f49c9ab5e6d34#diff-dd5636ea2eed792a7fdd42d789420a8eR3).

**Comment by tomas-knap** [comment]
Please revert and put to separate branch, we need to discuss about the changes. Changes in API should be always debated. For example, for sure it is not a good practise to change uv-dpu-config-vaadin/src/main/java/eu/unifiedviews/dpu/config/vaadin/ConfigDialogContext.java, just because certain DPus for certain deployment may need Encryption.  Either such extension should be in EncryptionConfigDialogContext e.g. (a special context for those which need enxryption) or ensured by helpers somehow.

**Comment by tomas-knap** [comment]
Sorry for switching back and forth, but please revert and prepare feature branch so that we can discuss before being available to others

**Comment by tomas-knap** [comment]
Reverted: https://github.com/UnifiedViews/Plugin-DevEnv/commit/1b4708358a43fe82b2a0298672bb575d9ce8e76b
