### ISSUE TITLE
Simplification of UV API modules (merge) 

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Plugin-DevEnv#21]
We have these modules covering API to UnifiedViews:
* uv-dataunit-files
* uv-dataunit-rdf
* uv-dataunit-relational
* uv-dpu-api
* uv-pom-api
* uv-dpu-config-vaadin (??? not sure if API or lib, is it implemented in Core?)

This split have no reason now, due to the fact that Core requires to install all these modules (jars) to be working. And there is also difficult to keep modules version independent (usualy all modules have version updated even code in module is not changed).

So the proposal is to merge API related modules into one module (uv-dpu-api suggested, not requires).

Benefits:
* simplified maintenance, change in any api part changes version in one place (one pom) including simplified dependency management in dpu.pom
* one jar file to be installed in frontend/backend
* easy extract of API into separate repository.

Disadvantages:
* Some DPUs have to be updated if not using properly dpu.pom (handwritten dependencies)

Proposal is to do it before release of API 2.0 not to have 'upgrade issues'.

**Comment by skodape** [comment]
As to the purpose of uv-dpu-config-vaadin this module contains Vaadin-configuration related definitions. It's part of API although it contains some abstract classes. This is caused by the fact that the used Vaadin "interface' is an abstract class.

**Comment by tomas-knap** [comment]
Think pros/cons, answer

**Comment by tomas-knap** [comment]
This will not be done for 2.0 release. Since it is just about organization of artifacts, it has no direct impact on DPU developers, existing DPUs, so this can be safely done later.

**Comment by skrchnavy** [comment]
@tomas-knap Due to the fact that in Plugins v2.1.0 all plugins will be updated to new API, it is good timing to do this change. 
Do you agree to include it?

**Comment by tomas-knap** [comment]
Lets postpone this, since we have all the processes in place which can handle this, versions may be changed all by one command, so we will do not spare much now. Also no direct impact for the user.

**Comment by tomas-knap** [comment]
@skrchnavy Lets discuss this on Skype first before being added to 2.2.0. I do not see any big value added (for now) and we have plenty of more pressing issues to be solved.
