### ISSUE TITLE
Cryptography support in helpers

### ISSUE THREAD

**Issue by eea01** [UnifiedViews/Plugin-DevEnv#22]
Relates to UnifiedViews/Core#320.

**Comment by eea01** [comment]
Requesting approval.

**Comment by eea01** [comment]
Not approved.

**Comment by skrchnavy** [comment]
Feature branch #27 was not approved but issue is valid, so not need to close,

**Comment by eea01** [comment]
Please close only #22, since new design does not include changes in Plugin-DevEnv.

**Comment by skrchnavy** [comment]
Based on above comment, issue closed.
