### ISSUE TITLE
ContextUtils.sendMessage() should allow translate also short message (caption) with parameters 

### ISSUE THREAD

**Issue by eea03** [UnifiedViews/Plugin-DevEnv#29]
In current implementation only long message can be parametrized (https://github.com/UnifiedViews/Plugin-DevEnv/blob/develop/uv-dpu-helpers/src/main/java/eu/unifiedviews/helpers/dpu/context/ContextUtils.java#L32-L74). During migration of eDemo DPUs I have encountered multiple occurrences of parameters also in short message. For such case, the ContextUtils.sendMessage() is useless.
Also sendError(), sendInfo() and sendWarn() methods should be able to translate caption with parameters.

I would also welcome sendMessage() method with only short message (or caption now) parameter, similarly to sendShortInfo() and sendShortWarn()

**Comment by tomas-knap** [comment]
I would consider this as an extension, which is easy to be done (basically the ConfigUtils.sendMessage can be taken as the inspiration). In case of bugs, it goes to @skodape, but in case of extensions, please @skrchnavy allocate

**Comment by skrchnavy** [comment]
@tomas-knap where is ConfigUtils.sendMessage available?

**Comment by skrchnavy** [comment]
@eea03 to implement sendShortMessage consistent with other similar methods.

**Comment by eea02** [comment]
I see a problem with implementation. In case we want to send parameters with short message and long message, we cannot have 2 varags method parameters. Also in current implementation is a bug in methods sendShortInfo and sendShortWarn where caption is translated twice. 
I dont see a reason for ContextUtils class at all. Its functionality should be done in DPU separately.

**Comment by tomas-knap** [comment]
The problems marked in the code of ContextUtils class
