### ISSUE TITLE
Access to user and global directories from DPU

### ISSUE THREAD

**Issue by skodape** [UnifiedViews/Plugin-DevEnv#3]
I think it can be useful to have access to DPUs directories (user,global) from ConfigurationDialog context - for example FIleHolder DPU can heavily utilize this feature.

**Comment by skrchnavy** [comment]
@skodape - Be aware of this feature, any DPU that manages files outside execution temporary dir is potencial candidate of troubles.
Example: DPU stores data in user dir.
* When DPU 'creates' (uploader) a file in such dir, it has to manage the the file
* In case that 2 DPUs requires same file, then you have to manage conflicts.
* When you want  to delete such DPU you have to manage that the file is also removed
* lot of other troubles
To ensure consistency, it is better to create special shared filesystem (meaning that the location is visible from UV and also for example as samba share or ftp server). Then you have external tools to manage files and keep the location consistent manualy.

**Comment by skodape** [comment]
As it's not actual now and many other properties are added now .. I suggest to close this issue.
