### ISSUE TITLE
Add support for 'About' in DPUs

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Plugin-DevEnv#31]
To be able to display description of DPU in more details (like help page).
Including internationalisation support.

**Comment by skrchnavy** [comment]
@skodape please find some commit where it is implemented

**Comment by skodape** [comment]
It affects two files:
[AbstractDialog](https://github.com/UnifiedViews/Plugin-DevEnv/blob/develop/uv-dpu-helpers/src/main/java/eu/unifiedviews/helpers/dpu/vaadin/dialog/AbstractDialog.java)
[AboutTab](https://github.com/UnifiedViews/Plugin-DevEnv/blob/develop/uv-dpu-helpers/src/main/java/eu/unifiedviews/helpers/dpu/vaadin/dialog/AboutTab.java)

The main functionality resided in AboutTab. In AbstractDialog the AboutTab object is only added to the dialog.

It should support internationalisation (just create about_sk.html) in some way (definitely not the best solution, but do the job).

The 'About' contains information about build time and content of about.html in DPU's resources - this file must be presented.

**Comment by skrchnavy** [comment]
a43f8e79935def0f376e8b9b145a2796470da269 is commit where current feature is implemented
