### ISSUE TITLE
Enable / disable optional features (tabs) via configuration

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Plugin-DevEnv#32]
This is created based on #24.
There is security risk that configuration is displayed in raw format to user.
So a mechanism to be able to disable this tab in all DPUs in one place shall be supported.

**Comment by skrchnavy** [comment]
This shall be unified with additional optional features (for example about tab, fault tolerance), to have common mechanism of configuration for all DPUs.

**Comment by eea03** [comment]
This was already implemented for about tab in https://github.com/UnifiedViews/Plugin-DevEnv/pull/35

**Comment by eea03** [comment]
Implemented in https://github.com/UnifiedViews/Plugin-DevEnv/pull/48; Ready to test

**Comment by skrchnavy** [comment]
PR #48 merged into develop ( see 7c7937b5ed22a4424b1d0e435a203bdcb89f427a) , so closing
