### ISSUE TITLE
Tabs are not localizable

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Plugin-DevEnv#36]
Support for tabs in DPU configurations (introduced in f90c61af749f7fc9a8c53cc0e7f58ee539511ce3, renamed in  ba7d066c58a5e66e520e577f2e76dec9c80310dc, finaly merged into develop in 7c5d9443ad9163838f09ed5b43763189510a370c) are not localisable)

**Comment by tomas-knap** [comment]
As discussed on Skype, @skrchnavy please assign somebody, if you encounter problems, let me know. 
Localization of this means to include translations to helpers.

**Comment by skrchnavy** [comment]
in pull request #35 - ready for review
