### ISSUE TITLE
Internalization support for DPUs

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Plugin-DevEnv#4]
To support localizable DPUs, DPU must know what language is expected to be used in configuration and also in messages (events).
For this purpose it is proposed to extend Plugin-DevEnv/uv-dpu-api/src/main/java/eu/unifiedviews/dpu/DPUContext.java to haver access to locales definition.

**Comment by mkl-eea-sk** [comment]
here https://github.com/UnifiedViews/Plugin-DevEnv/commit/ba17428d363e412238b3fce73165c07873e470ff
