### ISSUE TITLE
Write guideline for using About tab and README for DPUs

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Plugin-DevEnv#41]
Write guidelines how to use README and About tab - which info should be put there, under which format, etc. 

Requirements:
1) End user doc (About tab) should not contain all the information from README (version history, developer notes)
2) End user doc must be localizable (there is already support for that)
3) End user doc should use plaintext/simple markup, not HTML, so that its appearance may be controlled
4) The same info should not be specified twice - once in About tab and once in README

Note: Powered by CUNI helpers should be removed

Note: https://team.eea.sk/jira/browse/EDEM-159

**Comment by tomas-knap** [comment]
Powered by CUNI helpers should be removed

**Comment by skrchnavy** [comment]
@tomas-knap Current README.md format is not ideal also for DPU overview. It shall be split into:
* About (DPU description and configuration) - support for languages (About_<lang> or something similar)
* Versions (release note) - option is to use release notes github feature.
* Build (developer notes)

Readme could then be degraded to basic index of the DPU with initial table.

I vote for github markdown to cover also additional benefits of haveing DPUs on github.

**Comment by eea04** [comment]
When will this be implemented (meaning 'finished')?

**Comment by skrchnavy** [comment]
In progress, for details see: #54, UnifiedViews/Plugins#258

**Comment by tomas-knap** [comment]
Done, tutorial for writing documentation, https://grips.semantic-web.at/display/UDDOC/Tutorial%3A+Creating+skeleton+files+for+new+DPU
