### ISSUE TITLE
To correct wrong formating UnifiedViews template for eclipse

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Plugin-DevEnv#46]
based on report: https://github.com/UnifiedViews/Plugin-DevEnv/pull/45#issuecomment-101218580 it is requested to update eclipse formatting template to cope with the situation
*Problem for this particular formatting is that it handles it as it belongs to the deprecated tag; We should try to fix this in the template itself (if it is possible)*

When template ready, developers shall be informed via google groups unifiedviews-dev@googlegroups.com

**Comment by eea03** [comment]
Line length limit should be set to some reasonable value. I would suggest 120 characters, which is somehow recommended line length nowadays. Currently there is limit 300 set, which is too long. 

@tomas-knap: Do you agree with this change? However after this change all developers should be notified and probably all source code should be rerformated in one commit

**Comment by skrchnavy** [comment]
When reformat of code is approved, we shall also include changes related to UnifiedViews/Core#441

**Comment by mkl-eea-sk** [comment]
@skrchnavy please do not merge reformat with licensing, please. we will get + - whole files diff... licenses are easy to be solved. i can do it in a separate branch.

**Comment by skrchnavy** [comment]
@mkl-eea-sk please be aware that both changes affects (almost) all files. So when you run licensing you touch all files and have to merge them with all branches that are not finished. Also when you reformat all files you have to do the same operation.
So the goal is to do it together (in the same time not necessary in the same branch) in the time we have minimum open branches to avoid (minimize) difficult conflict solving in open branches.

**Comment by mkl-eea-sk** [comment]
Ok. But to my knowledge, licensing causes nearly no conflict. So 
licensing is easy to solve.

**Comment by skrchnavy** [comment]
Formating of pom.xml shall be included into template (see also UnifiedViews/Plugins#166)

**Comment by tomas-knap** [comment]
I added description how formatting of XML files should be specified to https://grips.semantic-web.at/display/UDDOC/Coding+Guidelines
