### ISSUE TITLE
To define versions of 3rd party components on one place

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Plugin-DevEnv#49]
Based on UnifiedViews/Core#380 
uv-pom/pom.xml shall contain versions of all 3rd party components used in UnifiedViews to define proper baseline for compilation and also for runtime to avoid different versions used in Core and in Plugins.

**Comment by eea03** [comment]
Should be solved by https://github.com/UnifiedViews/Plugin-DevEnv/pull/51
