### ISSUE TITLE
DPU shall have access to pipelineID and executionID

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Plugin-DevEnv#5]
In some cases DPU shall report also a context where it was included, that is what pipeline it runs and in which execution.

**Comment by skrchnavy** [comment]
@tomas-knap please decide, if this is good feature for DPUs. There are few use cases when DPU shall report such info, for example in ODN we need to inform catalogue about pipeline that produces data. Also there could be external (monitoring for example) system where we could report some data also related to pipeline or execution.

**Comment by tomas-knap** [comment]
Ok

**Comment by skodape** [comment]
@tomas-knap I would add dpuId as well, as all these values together can be used to generate unique ids, so we do not have to use Date.getTime)) or createTemp and similar solutions.

**Comment by skrchnavy** [comment]
Agreed with DpuInstanceID.

**Comment by skrchnavy** [comment]
@tomas-knap ready for review

**Comment by tomas-knap** [comment]
Ok

**Comment by skrchnavy** [comment]
#16 closed
