### ISSUE TITLE
Changes in URLValidator are not backward compatible

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Plugin-DevEnv#53]
New changes in dpu-helpers are not backward compatible. See:

1) https://github.com/UnifiedViews/Plugin-DevEnv/blob/master/uv-dpu-helpers/src/main/java/eu/unifiedviews/helpers/dpu/vaadin/validator/UrlValidator.java, Constructor with one param

2) https://github.com/UnifiedViews/Plugin-DevEnv/blob/develop/uv-dpu-helpers/src/main/java/eu/unifiedviews/helpers/dpu/vaadin/validator/UrlValidator.java, Constructor with one param is missing. 

Solution: The already release constructor must be still available - add the original constructor back. It must somehow work also with the constructor released in 2.0.2

**Comment by peterklimo** [comment]
fixed by d951ed5

**Comment by mkl-eea-sk** [comment]
another try https://github.com/UnifiedViews/Plugin-DevEnv/commit/52f9046cf4f0e6615996c04ac5529df5370d4ca0

**Comment by skrchnavy** [comment]
If working this shall be cherrypicked also into release branch.
