### ISSUE TITLE
make licensing information more clear and in line with general intentions

### ISSUE THREAD

**Issue by hanecak** [UnifiedViews/Plugin-DevEnv#55]
General intentions for UnifiedViews licensing is to:
* have UnifiedViews as Open Source
* have core set generic of DPUs as Open Source
* allow 3rd parties to create DPUs with other than Open Source licensing (i.e. commercial DPUs)

Now, while licensing for UnifiedViews-Core is quite specific, see https://github.com/UnifiedViews/Core/blob/master/README.md#licenses , licensing in UnifiedViews-Plugin-DevEnv is not explained to such level. And given current content of https://github.com/UnifiedViews/Plugin-DevEnv/blob/master/LICENSE.md (and lack of copyright and licensing info in individual source files) even ambiguous.

So, generally speaking, to fix this, we need minimally:
* add Licensing info into README.md
* specify, that (if I'm not mistaken) all code under UnifiedViews-Plugin-DevEnv is licensed under LGPLv3 (similarly to common, "library style" code in Core)
* keep only LGPLv3 in LICENSE.md

While at it, it would be nice to update also individual .java files as per https://www.gnu.org/licenses/gpl-howto.html, i.e. adding short copyright and licensing notices as comment at the beginning of all such files.

**Comment by skrchnavy** [comment]
Based on gpl-howto, each java file in Plugins-DevEnv licensed under LGPL shall have this text in the beginning of file:

```
    /*
   This file is part of UnifiedViews.

    UnifiedViews is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    UnifiedViews is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with UnifiedViews.  If not, see <http://www.gnu.org/licenses/>.
    */
```

**Comment by mkl-eea-sk** [comment]
I am reopening this issue to add maven  plugin which checks the license headers as a part of build process.
