### ISSUE TITLE
DPU shall have access to configuration parameters

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Plugin-DevEnv#6]
To be able globally configure DPUs, DPU shall have access to such properties.
Proposed is key/value, where user requests:
<code>
    string key = "myDPU.paramq";
    string cfgParam = getConfiguration(key);
</code>

**Comment by tomas-knap** [comment]
#9 is a blocker for this

**Comment by mkl-eea-sk** [comment]
? wasn't this issue meant "add method to dpucontext so DPU can read what is in backend.config" ?

**Comment by skrchnavy** [comment]
@mkl-eea-sk yes, it was original requirement but if we are able to configure DPUs another way then we can do that.
In general, it was requested to have similar feature as are achieved using environment variables in unix/linux, where any process could read it and use it.
Trigger was Locale support that required extension of interface, so for any new configuration we need in DPU could be achieved without such change.

**Comment by mkl-eea-sk** [comment]
Uhm, but those are two issues:
1. If one needs to get some static parameters into DPU, which are alike 
env. vars, or another values created and used by backend/frontend, we 
can put a method into DPUContext to retrieve Map<String, String> of 
'environment'
2. If one needs to generate configuration of next DPU in some previous 
DPU, for example:
1. e-filesDownload: download text file which contains SPARQL query
2. e-filesDownload: download some rdf
3. insert rdf from (2) into internal RDF store
4. t-sparql - run sparql from (1) on data from (3)
well, this is completely different issue.
So please, disjoint this two issues and tell which of them is this one.

**Comment by skrchnavy** [comment]
This is first case (sending a configuration to all DPUs).  But the way is not important, it could be defined in DB even for particular execution or another way.
And DPU is not pushed to consume the parameter, just if it need such parameter and receives it, it could work accordingly.

Example: I have 5 different DPUs that requires a common configuration parameter that is stable in production (URI prefix to use in metadata that are produced). So It can be configured once and these DPUs consumes it and others ignores it.

**Comment by mkl-eea-sk** [comment]
Thats third case,
you are now talking not about execution environment (stable parameters 
in production),
you want to extend it by something like 'configure it per pipeline' and 
next, you want something like 'values from this environment influences 
DATA produced', which definitely is not a good idea.

I would suggests to start with execution environment. One for all 
pipelines, at most runtime parameters which are different by nature 
(pipelineId) should be different for different pipelines. No 
configuration of this environment from gui, at most values from 
configuration files are imported by default.

The other cases you mention, should be elaborated somewhere else. Do we 
really need it? Where and why?

**Comment by skrchnavy** [comment]
I don't need to extend it but if this is the way how we can support stable configuration, it is also acceptable.
I definitely didn't ask for sending configuration from one DPU to another DPU.

**Comment by tomas-knap** [comment]
THis issue is about static configuration. DPU may be configured also dynamically by getting the configuration as the input. CUNI helper already supports dynamic configurations of DPUs. Dynamic configuration is alternative to the static conf described in this issue.

**Comment by skrchnavy** [comment]
#17 closed
