### ISSUE TITLE
Feature: relational Data Unit (interface+helpers)

### ISSUE THREAD

**Issue by skrchnavy** [UnifiedViews/Plugin-DevEnv#8]
Definition of interface and helper classes for tabularDataUnit for processing of tabular (structured) data.

**Comment by eea03** [comment]
Proposed interface in commit d9e786cb370a4dc1de7c7a84ec62226c2004305a

**Comment by tomas-knap** [comment]
See the comment under https://github.com/UnifiedViews/Plugin-DevEnv/pull/13, otherwise approved.

**Comment by skrchnavy** [comment]
#13  merged, so issue resolved

**Comment by skrchnavy** [comment]
#13 pull request closed
