### ISSUE TITLE
Align CUNI and EEA helpers

### ISSUE THREAD

**Issue by tomas-knap** [UnifiedViews/Plugin-DevEnv#9]
Motivations: 

1) Two helpers must be maintained 
2) Migration of DPUs using CUNI helpers to official Plugins helpers should be done after alignment of helpers, because CUNI DPUs use CUNI helpers, not available in official repo

Suggested steps:
1) Analyze which helpers in the official helpers is superseded by CUNI helpers completely, which is complementary (has some features on top of CUNI helpers)
2) Move CUNI helpers to official helpers, if they are duplicating, rename one, if certain is no longer needed, mark is as deprecated.

**Comment by tomas-knap** [comment]
For details - summary of actions, details: 
https://team.eea.sk/wiki/display/COMSODE/Aligning+CUNI+and+EEA+helpers

**Comment by skodape** [comment]
Branch https://github.com/UnifiedViews/Plugin-DevEnv/tree/feature/cuniMerge

**Comment by skrchnavy** [comment]
@skodape and @tomas-knap is this finalized? Please update status.
